import Footer from '@/components/Footer'
import Hero from '@/components/Hero'
import Project from '@/components/Project'
import Head from 'next/head'
import panaverseimg from "../../public/Panaverse.png"


export default function Home() {
  return (
    <>
      <Head>
        <title>Mahad Baig - UX Designer | Next.JS Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        <Hero />
        <Project 
        title = "PanaverseDAO"
        btnlink = "https://panaversedao-v2.vercel.app/"
        btntxt = "Live Preview"
        desc = "Panaverse DAO is Pakistan's largest community & training center of next gen Web3 & Metaverse developers."
        img = {panaverseimg}
        />
        <Footer />
     
      </main>
    </>
  )
}
